language: python
python:
  - "2.7"
install:
- source ./texlive_install.sh
- pip install https://github.com/dougalsutherland/arxiv-collector/archive/master.zip
addons:
  apt:
    packages:
    - zip
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- cd test
- latexmk
- arxiv-collector --get-latexmk latexmk
- arxiv-collector --debug  --latexmk ./latexmk test.tex


